name: Dotnet CI build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    env:
      SOLUTION: 'MediaManager.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Install dependencies
      run: dotnet restore $SOLUTION
    - name: Build & Package
      run: msbuild $SOLUTION -p:Configuration=Release -p:RestorePackages=false
