name: Dotnet CI

on:
  push:
    branches: [ develop, main ]

jobs:
  build:

    env:
      SOLUTION: 'ExoPlayer.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Install dependencies
      run: dotnet restore $SOLUTION
    - name: Build
      run: dotnet build $SOLUTION --configuration Release --no-restore
    - name: Create the package
      run: dotnet pack $SOLUTION --configuration Release
    - name: Publish the package to Nuget.org
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PUBLISH_TO_NUGET_ORG}} --skip-duplicate
